export const projects = [
  {
    name: "Visit Busan Survey",
    imageUrl: "https://lh3.googleusercontent.com/pw/AIL4fc_H5IcFhYH9ga8WPweTmivwtKzORm2zAUJqrajEsUoTZWQRLUqPWom9mWuEaXPR6tOF9PNv7korQ6ST8OML5AbF_lcY40EbSJM9_V4PT7-QCEwIB5YFW7aaPeo5Cu6OBhcPigHC1TVfkCnScwrK98K56w=w1678-h944-s-no?authuser=0",
    alt: "Busan survey form image",
    projectUrl: "",
    stack: "HTML | CSS",
    description: "A survey form for your trip to Busan.",
  },
  {
    name: "Product Landing Page",
    imageUrl: "https://lh3.googleusercontent.com/pw/AIL4fc8RpiZ_EzKHR77H9LUNpOr3zKGBlZvyQrHrR-J6ZmPkWLe1U5iXzs9AL8sIIIa4jJ6upl2LIpJLFVRnynyoHqkNLj-jpkUBxE5vOr8zZrPncHW0qB6VHanfavA9zSYyDDJMCIHKgHJj9KyHvgky5QAjjQ=w1799-h944-s-no?authuser=0",
    alt: "Landing page image",
    projectUrl: "",
    stack: "HTML | CSS",
    description: "A quick look at the wonders of our closest star, The Sun",
  },
  {
    name: "Tribute Page for Dr. Mae Carol Jemison",
    imageUrl:"https://lh3.googleusercontent.com/pw/AIL4fc81BhVad9-RedoeUSUpnel3r0KnZ-SReHUFCXK8jSQmFN7VkNBXEryQz2vUpO4eZ69cOSZ7EMqqhCmXfotsw4l17pcEFdL-0DJavyWccMRVtDqaMZYkbUYk05wfejC6QZe9sxoLaUQgZa-zbI4UEDv-EA=w1798-h944-s-no?authuser=0",
    alt: "Tribute page image",
    projectUrl: "",
    stack: "HTML | CSS",
    description: "A responsive page that was built for freeCodeCamp certification.",
  },
  {
    name: "Javascript Documentation Page",
    imageUrl: "https://lh3.googleusercontent.com/pw/AIL4fc_hDUW7rUqeeT5xwladIT_qSgKLQij7ZOIU3ldzrg28iTqD7s92M3l0vFnZsvgWu5KgCqUqW7HopzGJ2V6nQ4t8T3pKRXkkb5paPhIbXXAsR07KTuobYZYzypAoTr-DJpKfQSDv0RCwR7T72DoVP3G4ZQ=w1793-h944-s-no?authuser=0",
    alt: "Documentation page image",
    projectUrl: "",
    stack: "HTML | CSS",
    description: "Documentation.  Love me some documentation.",
  },
  {
    name: "Random Name Picker",
    imageUrl: "https://lh3.googleusercontent.com/pw/AIL4fc8i-LKtpWgRTVpE5BXoYqhLRxhSZQBwTfIK9pb0Z0cdKN1y9Ga7WBiB3au_wm2h4qxuSqmXt9gW6oYRXtC7ftbRSfgC3f3p4bt_ZCRjex_rAUWr4UPB4VBLqNwiLKZ2H2_aBBBNu45sZPXb0JdnIeHHgQ=w941-h975-s-no?authuser=0",
    alt: "Random Name Picker",
    projectUrl: "https://random-name-picker-alpha.vercel.app",
    description: "A random name picker used in class to choose students for various tasks.",
    stack: "Svelte",
    githubUrl: "https://www.github.com/GMSoudersJr/random-name-picker",
  },
  {
    name: "Global Surface Temperatures",
    imageUrl: "https://lh3.googleusercontent.com/pw/AIL4fc8Ge_Mr_pl6GAXzeIb9SF03KNF9FM_T6uXo7bda6FLBxVQghyOrNNVbbqAjvwNbnY500gFUKlD3NFkeFRbHgQP2GHnbkohLUMijdHoQdTw5q1yMEBFF3yJ-B4fKAU8daj5nHC-hatVClT4pYOKV4LAteA=w1900-h777-s-no?authuser=0",
    alt: "Data visualization image",
    projectUrl: "",
    description: "Data visualization of global surface temperatures for freeCodeCamp data visualization certification",
    stack: "D3.js | CSS",
  },
];

export const realProjects = [
  {
    name: "Random Name Picker",
    imageUrl: "https://lh3.googleusercontent.com/pw/AIL4fc8i-LKtpWgRTVpE5BXoYqhLRxhSZQBwTfIK9pb0Z0cdKN1y9Ga7WBiB3au_wm2h4qxuSqmXt9gW6oYRXtC7ftbRSfgC3f3p4bt_ZCRjex_rAUWr4UPB4VBLqNwiLKZ2H2_aBBBNu45sZPXb0JdnIeHHgQ=w941-h975-s-no?authuser=0",
    alt: "Random Name Picker",
    projectUrl: "https://random-name-picker-alpha.vercel.app",
    description: "A random name picker used in class to choose students for various tasks.",
    stack: "SVELTE",
    githubUrl: "https://www.github.com/GMSoudersJr/random-name-picker",
  },
  {
    name: "Timer",
    imageUrl: "https://lh3.googleusercontent.com/pw/AIL4fc9eqEPAo6tCDkTcWkViRFHSWj_SeXJIVcYMWSxmgfdwzTjw54E2UwQnRcS46_SIuerAJabuIrau_XNGezK2Bm_DOMNVn5r8OUth7khTdw3UccIU2SuC_2nq8_idQ2sO4yb0I7wAPP_jbqWbj0deqocVjA=w1080-h1080-s-no?authuser=0",
    alt: "Timer",
    projectUrl: "https://timer-pink-phi.vercel.app",
    description: "A countdown timer based on the Pomodoro Timer.",
    stack: "SVELTE",
    githubUrl: "https://www.github.com/GMSoudersJr/timer",
  },
];
